export const DataTypesMap = {
    char: 'string',
    varchar: 'string',
    text: 'string',
    tinytext: 'string',
    mediumtext: 'string',
    longtext: 'string',
    time: 'string',
    geometry: 'string',
    set: 'string',
    enum: 'string',
    integer: 'number',
    int: 'number',
    smallint: 'number',
    mediumint: 'number',
    bigint: 'number',
    double: 'number',
    decimal: 'number',
    numeric: 'number',
    float: 'number',
    year: 'number',
    tinyint: 'boolean',
    json: 'Object',
    date: 'string', // TODO: Add option for treating as date
    datetime: 'string',
    timestamp: 'string',
    tinyblob: 'Buffer',
    mediumblob: 'Buffer',
    longblob: 'Buffer',
    blob: 'Buffer',
    binary: 'Buffer',
    varbinary: 'Buffer',
    bit: 'Buffer',
}